# Generated by Django 3.1.7 on 2021-04-24 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20210414_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('out', models.BooleanField(default=False)),
                ('image', models.BinaryField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Holiday',
            new_name='tblHoliday',
        ),
        migrations.RenameModel(
            old_name='Present',
            new_name='tblPresent',
        ),
        migrations.RenameModel(
            old_name='User_details',
            new_name='tblUserdetails',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
